<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>

    <!-- Avalonia -->
    <PackageReference Include="Avalonia"
                      Version="12.0.0" />

    <PackageReference Include="Avalonia.Desktop"
                      Version="12.0.0" />

    <PackageReference Include="Avalonia.Themes.Fluent"
                      Version="12.0.0" />

    <PackageReference Include="Avalonia.Fonts.Inter"
                      Version="12.0.0" />

    <!-- SVG -->
    <PackageReference Include="Svg.Controls.Skia.Avalonia"
                      Version="12.0.0" />

    <!-- Diagnostics -->
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport"
                      Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">
        None
      </IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">
        All
      </PrivateAssets>
    </PackageReference>

  </ItemGroup>

  <!-- ChessGame Core -->
  <ItemGroup>

    <ProjectReference Include="..\ChessGame.Core\ChessGame.Core.csproj" />

  </ItemGroup>

  <!-- ===================================================== -->
  <!-- Chess SVG files                                      -->
  <!-- ===================================================== -->

  <ItemGroup>

    <None Update="Assets\Pieces\*.svg"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />

  </ItemGroup>

  <!-- ===================================================== -->
  <!-- Stockfish Engine                                     -->
  <!-- ===================================================== -->

  <ItemGroup>

    <Content Include="..\Engine\stockfish-windows-x86-64-avx2.exe">
      <Link>Engine\stockfish-windows-x86-64-avx2.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>

  </ItemGroup>

  <ItemGroup>

    <Content Include="Assets\Sounds\*.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>

  </ItemGroup>

</Project>